### ISSUE TITLE
Stuck on Running Test Cases

### ISSUE THREAD

**Issue by code-quant** [agrawal-d/competitive-programming-helper#1]
It got stuck on running test cases.

![image](https://user-images.githubusercontent.com/12227706/67483746-129e7000-f684-11e9-90bf-9a1a5de2b3fb.png)

**Comment by agrawal-d** [comment]
Hi!
This should be fixed in version 0.0.5 of the extensio. If you connect to the internet it should automatically get updated. To check force update, open extensions and search for Competitive Programming Helper. Try again after updating from there. 

If you still have the bug, I will test your code and try to fix the bug.

**Comment by code-quant** [comment]
I have reinstalled the extension several times. I am still facing same issue.

**Comment by agrawal-d** [comment]
> .testcase file is generated but I opened it, it is blank file.

This means the extension failed to parse the Codeforces page for testcases. Ill will check out the problem page and see what's causing the issue.

**Comment by agrawal-d** [comment]
I've found out the bug. As of now, the extension assumes that each testcase is in a new line. But it appears formatting of testcases is different in the HTML DOM for some problems. I will have to implement a virtual DOM. I will push an update to fix this soon and inform you.

Thank your for reporting the bug.

**Comment by code-quant** [comment]
Here are the files generated + .cpp file. 

[Codeforces.zip](https://github.com/agrawal-d/competitive-programming-helper/files/3767462/Codeforces.zip)

**Comment by agrawal-d** [comment]
I have fixed the issue and pushed an update ( version 0.0.6 ).
Please update the extension and test it, and do let me know if it works/doesn't work, so that I may close the issue.

**Comment by code-quant** [comment]
It seems to be working now but I am getting "Process was killed" .

![image](https://user-images.githubusercontent.com/12227706/67488799-0cad8c80-f68e-11e9-984a-cb2932014e10.png)

**Comment by code-quant** [comment]
Tested it on other code. It worked like charm.

**Comment by agrawal-d** [comment]
> Tested it on other code. It worked like charm.
> ![image](https://user-images.githubusercontent.com/12227706/67489056-86457a80-f68e-11e9-909e-e9703a0006c4.png)

Great!

**Comment by agrawal-d** [comment]
Closing issue as it appears to be resolved. If you still have any other issue/feature requests, please create another issue.
