### ISSUE TITLE
Wrong expected output and verdict

### ISSUE THREAD

**Issue by ones-and-zeroes** [agrawal-d/competitive-programming-helper#12]
I am getting random expected result and hence random passed and failed verdicts with my code. I have checked that the output should pass for the given test case.
For no change in code I got these different outputs just by running testcases again.
![test1](https://user-images.githubusercontent.com/56965282/76241510-1ad60100-625b-11ea-9550-6305dbf7f545.jpg)
![test2](https://user-images.githubusercontent.com/56965282/76241520-1f021e80-625b-11ea-8b9b-71c46df2009c.jpg)
![test3](https://user-images.githubusercontent.com/56965282/76241532-23c6d280-625b-11ea-98df-75be6bb62460.jpg)
![test4](https://user-images.githubusercontent.com/56965282/76241536-24f7ff80-625b-11ea-984a-60ca234028e3.jpg)

Though I know there should not be any relation to what the code is yet I link it here
[C_Adding_Powers.txt](https://github.com/agrawal-d/competitive-programming-helper/files/4308169/C_Adding_Powers.txt)

Judging by the lack of issues, I believe there is some problem on my end so help me with that.

**Comment by agrawal-d** [comment]
Hi! Thanks for the report. Can you please comment with the link to the problem you are trying to solve? It'll help in the debugging process.

**Comment by ones-and-zeroes** [comment]
Sure, here's the [link](https://codeforces.com/contest/1312/problem/C).

**Comment by agrawal-d** [comment]
Thanks for the link. I just tested out your code for this problem, and the extension is working fine for me, even after running it several times. I really can't think of why it's giving different outputs at different times for you!

**Comment by agrawal-d** [comment]
Closing as it's stale. Feel free to create a new issue if the problem occurs again.
