### ISSUE TITLE
What is the port number used ?? because after clicking the add-ons the file is not opening in vscode

### ISSUE THREAD

**Issue by DeepanshuJha** [agrawal-d/competitive-programming-helper#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gandhi24** [comment]
It is 27121. But adding that custom port isn't working for me. I am facing the same issue since yesterday. @agrawal-d

**Comment by agrawal-d** [comment]
Thanks for the report. Actually, you no longer have to enter custom port number anymore if you use the latest version of Competitive Programming Helper. Anyway, this feature only works if you have a folder open in VS Code. Do you have a folder open?

**Comment by Gandhi24** [comment]
Yes..I think it's the new vscode update. I reverted back to 1.42 and it's working fine now.

**Comment by agrawal-d** [comment]
Okay. Thanks! That will help me with the debugging.

**Comment by adzo261** [comment]
Same issue for me with new vscode update.

**Comment by agrawal-d** [comment]
Hi! I'm aware of this issue, several people have reported it. I'll look at it as soon as possible.

**Comment by grinrag** [comment]
+1 for me.

I have just installed this plugin for first time and it doesn't work.
I am pressing the '+' button, but nothing is happening.

**Comment by agrawal-d** [comment]
Hi! I've fixed this issue in the latest update. Please update the extension to the latest version. It should update automatically, but to be sure, go to extensions and search for 'competitive programming helper' and click update.

If you still face any problems, feel free to open a new issue.

**Comment by agrawal-d** [comment]
Version 3.3.0
