### ISSUE TITLE
Does not detect test case in latest VSCode update

### ISSUE THREAD

**Issue by karan221** [agrawal-d/competitive-programming-helper#14]
**Description**
After updating VSCode from version 1.42 to 1.43 the test case are not fetched via the Competitive Companion extension. Test case can be generated manually or by codeforces problem link.

**To Reproduce**
1. Update VSCode from 1.42 to 1.43

**Expected behavior**
Test cases not fetched from the browser

**Desktop :**
 - OS: Windows 10
 - Browser: Mozzila firefox 74

**Comment by agrawal-d** [comment]
Thanks for the report. I'll investigate this. Can you check if a folder was open in VS Code when you clicked on the buttomn? This feature only works when a folder is open.

**Comment by karan221** [comment]
> 
> 
> Thanks for the report. I'll investigate this. Can you check if a folder was open in VS Code when you clicked on the buttomn? This feature only works when a folder is open.

Yes a folder is open.

**Comment by HelmiB** [comment]
Temporary solution, downgrade VSC to version 1.42 (January 2020).

Don;t forget to disable auto-update.

**Comment by agrawal-d** [comment]
I'll look into this issue as soon as possible. I'm travelling righ now.

Divyanshu Agrawal

________________________________

**Comment by agrawal-d** [comment]
Hi! I've fixed this issue in the latest update. Please update the extension to the latest version. It should update automatically, but to be sure, go to extensions and search for 'competitive programming helper' and click update.

If you still face any problems, feel free to open a new issue.

**Comment by agrawal-d** [comment]
Version 3.3.0
