### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by code-quant** [agrawal-d/competitive-programming-helper#2]
1. Please delete the temporary files generated (.testcases, .bin) after execution.
2. Add Theming option, Auto adapt to current color scheme or option to manually change the colors.
3. Option to clean up files and remove the Codeforces URL 1st line from files after sucessful execution.

Really a great tool, saves up lots of time. Thanks!

**Comment by agrawal-d** [comment]
I have addressed all three of your requests. Please update your extension and test it. Do let me know if it works/does not work as expected.

**Comment by code-quant** [comment]
Updated, Extension works like charm. Theme is also good now. I am happy with what this tool is able to do. To clear/clean bin and tcs files generated, I have made a .bat script which cleans up my directory. Everything works fine for now. If I feel need of any additional feature, I will post a feature request. Thanks!
