### ISSUE TITLE
NOT parsing task

### ISSUE THREAD

**Issue by Imtiaz246** [agrawal-d/competitive-programming-helper#23]
Before update it was working fine but after the latest update it's not parsing task idk why?

**Comment by AJ-54** [comment]
The same happens with me

**Comment by agrawal-d** [comment]
It appears to be working for me. Can you please 
1. Uninstall and reinstall the extension.
1. Make sure a folder is open in VS Code.

and try again?

**Comment by Imtiaz246** [comment]
I did those steps (1&2) multiple time's. I've also tried on different version of VScode including latest version,  unfortunately it's still the same.

**Comment by Gandhi24** [comment]
I am also facing the same problem since yesterday. I believe it's the same as [#14 ](url).

**Comment by Imtiaz246** [comment]
@Gandhi24 it might not same as #14 because I've tried various version's of VS-code. 

> 
> 
> I am also facing the same problem since yesterday. I believe it's the same as [#14 ](https://github.com/agrawal-d/competitive-programming-helper/issues/14).

**Comment by hobo0xcc** [comment]
Try changing "default language" (File -> Preferences -> Settings -> Extensions -> Competitive Programming Helper -> Default Language).
I think c92b6af is the cause.

**Comment by Imtiaz246** [comment]
> 
> 
> Try changing "default language" (File -> Preferences -> Settings -> Extensions -> Competitive Programming Helper -> Default Language).
> I think [c92b6af](https://github.com/agrawal-d/competitive-programming-helper/commit/c92b6af0ef2be8238e6f8bc90f3eb6e7b9a8e496) is the cause.

Thanks @hobo0xcc . It worked.

**Comment by agrawal-d** [comment]
Sorry for the trouble! I've fixed this in a commit. Thanks for reporting.
