### ISSUE TITLE
Automatically add problem url in file as commented line.

### ISSUE THREAD

**Issue by archie9211** [agrawal-d/competitive-programming-helper#24]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
it should append commented line something like following :

![ss](https://user-images.githubusercontent.com/25462010/79018118-9eec1300-7b90-11ea-9660-18be6e5d4382.png)

**Comment by agrawal-d** [comment]
Some people dislike such a comment - in fact it was originally a feature and was later removed when people requested. I may add this as an optional feature in the future.
