### ISSUE TITLE
Wrong Evaluation

### ISSUE THREAD

**Issue by code-quant** [agrawal-d/competitive-programming-helper#5]
I have tested a code. Output matches the Result but still it is showing Wrong/Failed. 
I have also evaluated the code on codeforces and it gets AC. 

[1251A_BrokenKeyboard.txt](https://github.com/agrawal-d/competitive-programming-helper/files/3772066/1251A_BrokenKeyboard.txt)

![image](https://user-images.githubusercontent.com/12227706/67571881-ab032600-f752-11e9-833b-236c06cc7c41.png)

**Comment by agrawal-d** [comment]
I am unable to reproduce the error. I am getting Passed on my system.
![image](https://user-images.githubusercontent.com/7714968/67581215-456c6500-f765-11e9-9dba-4b75fbd380d6.png)

A similar issue was reported by another user, and in that case too, I got the Passed verdict.
Which OS  are you using?

**Comment by code-quant** [comment]
I am using Windows 10 x64
I have MinGW minimal compiler installed + I am using code runner extension for code compilation.

**Comment by agrawal-d** [comment]
Unrelated to this issue, you don't need another extension to compile code. This one does it automatically.

**Comment by code-quant** [comment]
Code Runner extension just cuts off the task and launch configuration.

**Comment by agrawal-d** [comment]
I have confirmed that it fails in Windows PCs. It does not fail in Linux PCs.

**Comment by agrawal-d** [comment]
Found the source of the problem. In Windows, a newline is saved as \r\n whereas in Linux a newline is saved as \n. Will try to fix it.

**Comment by agrawal-d** [comment]
The latest release, 0.0.8 should fix it. Please update your extension and hopefully, the issue is resolved. Thank you for reporting the issue.
