### ISSUE TITLE
Competitive Companion Integration

### ISSUE THREAD

**Issue by Salil03** [agrawal-d/competitive-programming-helper#6]
You can use https://github.com/jmerle/competitive-companion  to parse testcases automatically. It also supports many websites.

**Comment by agrawal-d** [comment]
Thanks for your idea! I'm aware of the extension, yet did not use it because I did not want any dependencies in my extension. 
However, if I get time in the future, I might integrate it.

I'm closing this issue for now. Let me know if you have anything else to say.

**Comment by agrawal-d** [comment]
@Salil03 FYI it has been implemented in the latest release.
