### ISSUE TITLE
Populate newly generated file from Competitive Companion with my default template

### ISSUE THREAD

**Issue by adzo261** [agrawal-d/competitive-programming-helper#9]
**Is your feature request related to a problem? Please describe.**
Currently, with Competitive Companion, it generates a new empty `.cpp` file. <br> However, I would like to populate it with my default template for cp.

**Describe the solution you'd like**
I would expect settings variable, where I will give the path of my `.cpp` file from which you can take contents and paste every time a new file is created.

**Comment by agrawal-d** [comment]
Thanks for requesting the feature!
This would be a redundant feature, as VS Code already supports snippets.
Have you tried using & creating custom snippets?

**Comment by adzo261** [comment]
Oh yes, my bad. Thanks for cp helper anyway. You can safely delete this issue.

**Comment by hugleo** [comment]
You can load automatically a snippet name that I define when you create the file ;-)
